//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.11.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from .\HexquisiteLevel.g4 by ANTLR 4.11.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="HexquisiteLevelParser"/>.
/// </summary>
#pragma warning disable CS3021
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.11.1")]
[System.CLSCompliant(false)]
public interface IHexquisiteLevelListener : IParseTreeListener {
#pragma warning restore CS3021
	/// <summary>
	/// Enter a parse tree produced by <see cref="HexquisiteLevelParser.level"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLevel([NotNull] HexquisiteLevelParser.LevelContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="HexquisiteLevelParser.level"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLevel([NotNull] HexquisiteLevelParser.LevelContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="HexquisiteLevelParser.version"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVersion([NotNull] HexquisiteLevelParser.VersionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="HexquisiteLevelParser.version"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVersion([NotNull] HexquisiteLevelParser.VersionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="HexquisiteLevelParser.shapes"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterShapes([NotNull] HexquisiteLevelParser.ShapesContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="HexquisiteLevelParser.shapes"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitShapes([NotNull] HexquisiteLevelParser.ShapesContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="HexquisiteLevelParser.keyshape"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterKeyshape([NotNull] HexquisiteLevelParser.KeyshapeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="HexquisiteLevelParser.keyshape"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitKeyshape([NotNull] HexquisiteLevelParser.KeyshapeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="HexquisiteLevelParser.shape"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterShape([NotNull] HexquisiteLevelParser.ShapeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="HexquisiteLevelParser.shape"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitShape([NotNull] HexquisiteLevelParser.ShapeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="HexquisiteLevelParser.goals"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterGoals([NotNull] HexquisiteLevelParser.GoalsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="HexquisiteLevelParser.goals"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitGoals([NotNull] HexquisiteLevelParser.GoalsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="HexquisiteLevelParser.walls"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterWalls([NotNull] HexquisiteLevelParser.WallsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="HexquisiteLevelParser.walls"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitWalls([NotNull] HexquisiteLevelParser.WallsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="HexquisiteLevelParser.piece"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPiece([NotNull] HexquisiteLevelParser.PieceContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="HexquisiteLevelParser.piece"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPiece([NotNull] HexquisiteLevelParser.PieceContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="HexquisiteLevelParser.anchor"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAnchor([NotNull] HexquisiteLevelParser.AnchorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="HexquisiteLevelParser.anchor"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAnchor([NotNull] HexquisiteLevelParser.AnchorContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="HexquisiteLevelParser.vector2int"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVector2int([NotNull] HexquisiteLevelParser.Vector2intContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="HexquisiteLevelParser.vector2int"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVector2int([NotNull] HexquisiteLevelParser.Vector2intContext context);
}
